<a href="https://colab.research.google.com/github/mailtobiswajit02-rgb/Python-Project/blob/main/Copy_of_SVD_Netflix(June)%20Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
netflix_dataset = pd.read_csv("/content/drive/MyDrive/netflix/combinedNetflixData (2).txt", header = None, names=['CustId', 'Rating'], usecols=[0,1])

In [ ]:
netflix_dataset.head(20)

     CustId  Rating
0        1:     NaN
1   1488844     3.0
2    822109     5.0
3    885013     4.0
4     30878     4.0
5    823519     3.0
6    893988     3.0
7    124105     4.0
8   1248029     3.0
9   1842128     4.0
10  2238063     3.0
11  1503895     4.0
12  2207774     5.0
13  2590061     3.0
14     2442     3.0
15   543865     4.0
16  1209119     4.0
17   804919     4.0
18  1086807     3.0
19  1711859     4.0

In [ ]:
netflix_dataset.tail(50)

           CustId  Rating
24058213   773477     2.0
24058214  1929124     1.0
24058215   940117     1.0
24058216   654125     1.0
24058217   680004     2.0
24058218   829708     3.0
24058219   987337     2.0
24058220    16967     2.0
24058221  2068034     1.0
24058222  2496494     1.0
24058223  1179450     3.0
24058224   459488     2.0
24058225   156866     1.0
24058226   723223     1.0
24058227   426005     3.0
24058228  1393365     2.0
24058229   101554     4.0
24058230   174879     2.0
24058231   692418     3.0
24058232  2431740     4.0
24058233  1836014     3.0
24058234  1960927     1.0
24058235  2385226     1.0
24058236  1997469     2.0
24058237   811530     4.0
24058238  1083336     5.0
24058239  1309223     1.0
24058240   604335     4.0
24058241   307404     2.0
24058242  1334851     3.0
24058243  1061120     3.0
24058244  1852040     1.0
24058245   268846     4.0
24058246  2368103     2.0
24058247   529787     4.0
24058248   441248     4.0
24058249  2092745     5.0
24058250   555962     5.0
24058251   303969     2.0
24058252   654591     3.0
24058253   272857     4.0
24058254   185372     1.0
24058255  2219917     3.0
24058256  1796454     1.0
24058257  2562830     4.0
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

In [ ]:
netflix_dataset.shape

(24058263, 2)

EDA -- null values, duplicate,

In [ ]:
netflix_dataset.head()

    CustId  Rating
0       1:     NaN
1  1488844     3.0
2   822109     5.0
3   885013     4.0
4    30878     4.0

In [ ]:
netflix_dataset.isnull().sum()

CustId       0
Rating    4499
dtype: int64

## Total number of movies

In [ ]:
# number of movies = null values inside rating column

movie_count = netflix_dataset.isnull().sum()['Rating']
movie_count

4499

Total customer count

In [ ]:
total_count=netflix_dataset['CustId'].nunique()
total_count

475257

In [ ]:
customer_count = total_count - movie_count
customer_count

470758

## Total Reviews

In [ ]:
rating_count = netflix_dataset['CustId'].count() - movie_count
rating_count

24053764

Separate movie if from customer id

In [ ]:
movie_id = None # movie id is a variable which will iterate through all the movie ids.
movie_id_per_row = []

for i in netflix_dataset['CustId']:
  if ":" in i:
    movie_id = int(i.replace(":","")) # store the value of movie id without colon
  movie_id_per_row.append(movie_id)

In [ ]:
movie_id_per_row

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
netflix_dataset['Movie_ID'] = movie_id_per_row

In [ ]:
netflix_dataset.head()

    CustId  Rating  Movie_ID
0       1:     NaN         1
1  1488844     3.0         1
2   822109     5.0         1
3   885013     4.0         1
4    30878     4.0         1

In [ ]:
netflix_dataset.dropna(inplace = True)

In [ ]:
netflix_dataset.isnull().sum()

CustId      0
Rating      0
Movie_ID    0
dtype: int64

In [ ]:
netflix_dataset.head()

    CustId  Rating  Movie_ID
1  1488844     3.0         1
2   822109     5.0         1
3   885013     4.0         1
4    30878     4.0         1
5   823519     3.0         1

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   CustId    object
 1   Rating    float64
 2   Movie_ID  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
# Convert CustId to int

netflix_dataset['CustId'] = netflix_dataset['CustId'].astype('int')

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   CustId    int64
 1   Rating    float64
 2   Movie_ID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
netflix_dataset.head()

    CustId  Rating  Movie_ID
1  1488844     3.0         1
2   822109     5.0         1
3   885013     4.0         1
4    30878     4.0         1
5   823519     3.0         1

## Create a list of movies with very few ratings

In [ ]:
summary = netflix_dataset.groupby("Movie_ID")['Rating'].agg(['count'])
summary

          count
Movie_ID
1           547
2           145
3          2012
4           142
5          1140
...         ...
4495        614
4496       9519
4497        714
4498        269
4499        428

[4499 rows x 1 columns]

In [ ]:
# now we will keep a benchmark at 60th percentile

movie_benchmark = round(np.percentile(summary['count'], 60, method ='linear'))

In [ ]:
movie_benchmark

908

In [ ]:
drop_movie_list = summary[summary['count']<movie_benchmark].index

In [ ]:
drop_movie_list

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='Movie_ID', length=2699)

In [ ]:
summary_cust =  netflix_dataset.groupby("CustId")['Rating'].agg(['count'])
summary_cust

         count
CustId
6          153
7          195
8           21
10          49
25           4
...        ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62

[470758 rows x 1 columns]

In [ ]:
cust_benchmark = round(np.percentile(summary_cust['count'], 60, method='linear'))

In [ ]:
cust_benchmark

36

In [ ]:
drop_cust_list = summary_cust[summary_cust['count']<cust_benchmark].index
drop_cust_list

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustId', length=282042)

In [ ]:
netflix_dataset = netflix_dataset[~netflix_dataset['Movie_ID'].isin(drop_movie_list)]

# so it checks all the movies that are present in the drop movie list using membership operator
# then using negation operator ~ we filter out all those rows
# finally your data has all the rows with the movie ids not present in the drop movie list.

In [ ]:
netflix_dataset = netflix_dataset[~netflix_dataset['CustId'].isin(drop_cust_list)]

In [ ]:
netflix_dataset.shape

(19695836, 3)

In [ ]:
df_title = pd.read_csv("/content/drive/MyDrive/netflix/movies (1) (1).csv", encoding = "ISO-8859-1", usecols=[0,1,2])

In [ ]:
df_title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB

In [ ]:
# rename movieID in df_title to Movie_ID
df_title.rename(columns={"movieID":"Movie_ID"}, inplace = True)

In [ ]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [ ]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)
Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 38.4 MB/s eta 0:00:00
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.5

In [ ]:
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

In [ ]:
reader = Reader()

In [ ]:
data = Dataset.load_from_df(netflix_dataset[['CustId', 'Movie_ID', "Rating"]][:100000], reader)

In [ ]:
data

In [ ]:
model = SVD()

In [ ]:
cross_validate(model, data, measures = ['RMSE'], cv = 3)

{'test_rmse': array([1.022826  , 1.02067262, 1.01662955]),
 'fit_time': (1.8553862571716309, 1.2998201847076416, 1.2515339851379395),
 'test_time': (0.30767154693603516, 0.4111287593841553, 0.1758561134338379)}

In [ ]:
netflix_dataset['CustId']

696          712664
697         1331154
698         2632461
699           44937
700          656399
             ...
24056842    1055714
24056843    2643029
24056844     267802
24056845    1559566
24056846     293198
Name: CustId, Length: 19695836, dtype: int64

In [ ]:
user_rating = netflix_dataset[netflix_dataset['CustId'] == 1331154]

In [ ]:
user_rating

           CustId  Rating  Movie_ID
697       1331154     4.0         3
5178      1331154     4.0         8
31460     1331154     3.0        18
92840     1331154     4.0        30
224761    1331154     3.0        44
...           ...     ...       ...
23439584  1331154     4.0      4389
23546489  1331154     2.0      4402
23649431  1331154     4.0      4432
23844441  1331154     3.0      4472
23985561  1331154     4.0      4488

[253 rows x 3 columns]

In [ ]:
user_1331154 = df_title.copy()
user_1331154

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund fÃ¼r's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [ ]:
# Remove the less rated movies

user_1331154 = user_1331154[~user_1331154['movieId'].isin(drop_movie_list)]

In [ ]:
user_1331154

       movieId                               title                    genres
2            3             Grumpier Old Men (1995)            Comedy|Romance
4            5  Father of the Bride Part II (1995)                    Comedy
5            6                         Heat (1995)     Action|Crime|Thriller
7            8                 Tom and Huck (1995)        Adventure|Children
15          16                       Casino (1995)               Crime|Drama
...        ...                                 ...                       ...
27273   131254       Kein Bund fÃ¼r's Leben (2007)                    Comedy
27274   131256       Feuer, Eis & Dosenbier (2002)                    Comedy
27275   131258                  The Pirates (2014)                 Adventure
27276   131260                 Rentun Ruusu (2001)        (no genres listed)
27277   131262                    Innocence (2014)  Adventure|Fantasy|Horror

[24640 rows x 3 columns]

In [ ]:
user_1331154["Estimated_Score"] = user_1331154['movieId'].apply(lambda x:model.predict(1331154,x).est)

/tmp/ipykernel_19010/893928434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_1331154["Estimated_Score"] = user_1331154['movieId'].apply(lambda x:model.predict(1331154,x).est)

In [ ]:
user_1331154.sort_values("Estimated_Score", ascending = False, inplace = True)

/tmp/ipykernel_19010/2840260142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_1331154.sort_values("Estimated_Score", ascending = False, inplace = True)

In [ ]:
user_1331154.head()

,movieId,title,genres,Estimated_Score
4,5,Father of the Bride Part II (1995),Comedy,4.094841
24,25,Leaving Las Vegas (1995),Drama|Romance,3.915176
7,8,Tom and Huck (1995),Adventure|Children,3.849550
19061,94831,Leadbelly (1976),Drama,3.612944
19071,94896,Bernie (2011),Comedy|Crime|Drama,3.612944